<a href="https://colab.research.google.com/github/kelvynlukito/DataScience_Practice_LogisticRegressionClassifier/blob/main/DataScience_Practice_LogisticRegressionClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Logistic Regression**

---

# **Import Libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# **Import Dataset**

In [2]:
df = pd.read_csv('/content/Social_Network_Ads.csv')
df

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [8]:
df.head()

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [9]:
df.tail()

     Age  EstimatedSalary  Purchased
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB

In [13]:
df.describe()

              Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

In [17]:
df.shape

(400, 3)

In [14]:
df.isnull().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [15]:
df.isna().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [6]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

# **Splitting Dataset to Tranining & Testing**

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [35]:
print(X_train)

[[    29  28000]
 [    45  22000]
 [    46 117000]
 [    32  18000]
 [    22  81000]
 [    25  87000]
 [    48  33000]
 [    35  58000]
 [    47  23000]
 [    26  32000]
 [    32 135000]
 [    60  34000]
 [    52  21000]
 [    38  55000]
 [    25  90000]
 [    58  38000]
 [    49  88000]
 [    37  78000]
 [    35  77000]
 [    34  43000]
 [    20  49000]
 [    46  88000]
 [    31  34000]
 [    47  30000]
 [    35  50000]
 [    39  96000]
 [    33 113000]
 [    49  86000]
 [    45  79000]
 [    44  39000]
 [    41  59000]
 [    42  53000]
 [    35  73000]
 [    41  72000]
 [    27  96000]
 [    30 116000]
 [    41  52000]
 [    41  52000]
 [    20  82000]
 [    46  41000]
 [    27  31000]
 [    35  71000]
 [    49  28000]
 [    35  91000]
 [    37  75000]
 [    32 117000]
 [    36  75000]
 [    20  86000]
 [    38  50000]
 [    49  36000]
 [    40  65000]
 [    37  77000]
 [    60  46000]
 [    48 138000]
 [    40  71000]
 [    36  63000]
 [    26  81000]
 [    33  31000]
 [    41  51000]
 [    46  74000]
 [    18  82000]
 [    37  33000]
 [    35  53000]
 [    28  59000]
 [    37  71000]
 [    18  44000]
 [    38  61000]
 [    35  65000]
 [    31  66000]
 [    47  25000]
 [    42 104000]
 [    19  19000]
 [    21  72000]
 [    28  32000]
 [    52 150000]
 [    53 104000]
 [    25  80000]
 [    26  72000]
 [    26  15000]
 [    40 142000]
 [    35  38000]
 [    57 122000]
 [    41  87000]
 [    24  89000]
 [    37  52000]
 [    35 108000]
 [    32 100000]
 [    35 147000]
 [    19  26000]
 [    46  82000]
 [    47 105000]
 [    45  45000]
 [    38  51000]
 [    37  93000]
 [    29  43000]
 [    41  30000]
 [    40  60000]
 [    27  88000]
 [    27  90000]
 [    39  71000]
 [    23  28000]
 [    51 146000]
 [    23  63000]
 [    37  80000]
 [    40  47000]
 [    48  29000]
 [    35  59000]
 [    26  30000]
 [    39 106000]
 [    28  84000]
 [    59  76000]
 [    40  57000]
 [    35  97000]
 [    26  86000]
 [    41  63000]
 [    29  47000]
 [    26  17000]
 [    58  23000]
 [    30  62000]
 [    25  33000]
 [    59  29000]
 [    28  37000]
 [    39  77000]
 [    47 107000]
 [    52 138000]
 [    29  43000]
 [    27 137000]
 [    24  55000]
 [    40  72000]
 [    21  16000]
 [    57  26000]
 [    30 135000]
 [    48 119000]
 [    40  57000]
 [    35  75000]
 [    28  44000]
 [    37  74000]
 [    35  27000]
 [    37  79000]
 [    32 120000]
 [    29  75000]
 [    30  17000]
 [    25  79000]
 [    40 107000]
 [    24  19000]
 [    41  72000]
 [    38  61000]
 [    36 144000]
 [    42  64000]
 [    48  33000]
 [    48  30000]
 [    23  20000]
 [    55 130000]
 [    29 148000]
 [    42  65000]
 [    27  54000]
 [    37  55000]
 [    25  22000]
 [    59 143000]
 [    42  54000]
 [    27  17000]
 [    47  49000]
 [    28  59000]
 [    33  69000]
 [    31  68000]
 [    35  23000]
 [    35  22000]
 [    57  33000]
 [    30 107000]
 [    46  23000]
 [    41  60000]
 [    33  41000]
 [    33  60000]
 [    47  47000]
 [    28  55000]
 [    45  32000]
 [    35  75000]
 [    59  42000]
 [    47  50000]
 [    47  51000]
 [    35  79000]
 [    39  42000]
 [    40  78000]
 [    23  48000]
 [    39  75000]
 [    35  57000]
 [    55  39000]
 [    31  71000]
 [    28 123000]
 [    42  80000]
 [    40  59000]
 [    48  74000]
 [    21  88000]
 [    53  72000]
 [    27  58000]
 [    35  47000]
 [    28  89000]
 [    26  80000]
 [    32 117000]
 [    42  75000]
 [    33 149000]
 [    41  80000]
 [    31  58000]
 [    39 134000]
 [    27  20000]
 [    29  83000]
 [    19  70000]
 [    19  85000]
 [    29  61000]
 [    39 134000]
 [    31  76000]
 [    41  72000]
 [    26  80000]
 [    40  61000]
 [    35  25000]
 [    48  96000]
 [    42 149000]
 [    28  79000]
 [    51 134000]
 [    33  28000]
 [    42  54000]
 [    45  22000]
 [    37  57000]
 [    34 112000]
 [    35  39000]
 [    22  27000]
 [    35  72000]
 [    39  59000]
 [    20  74000]
 [    46  32000]
 [    26  43000]
 [    29  83000]
 [    55 125000]
 [    37 146000]
 [    45 131000]
 [    33  43000]
 [    41  45000]
 [    42  79000]
 [    37 137000]
 [    24  84000]
 [    32  18000]
 [    56 104000]
 [    49  39000]
 [    28  85000]
 [    53 143000]
 [    30  89000]
 [    57  60000]
 [    40  75000]
 [    41  79000]
 [    20  82000]
 [    22  55000]
 [    35  88000]
 [    54  70000]
 [    31  15000]
 [    50  36000]
 [    42  65000]
 [    34  43000]
 [    42 108000]
 [    54  26000]
 [    19  21000]
 [    36  50000]
 [    37  70000]
 [    36 126000]
 [    47  20000]
 [    30  79000]
 [    59  83000]
 [    29  80000]
 [    43 112000]
 [    38  80000]
 [    58 144000]
 [    36 125000]
 [    49  28000]
 [    18  52000]
 [    30  15000]
 [    59  88000]
 [    27  57000]
 [    38  71000]
 [    31  89000]
 [    47  34000]
 [    31  74000]
 [    37  72000]
 [    40  57000]
 [    59 130000]
 [    49  65000]
 [    48  90000]
 [    46  22000]
 [    54 104000]
 [    35  20000]
 [    49 141000]
 [    48  41000]
 [    35  55000]
 [    36  60000]
 [    32 150000]
 [    18  68000]
 [    24  55000]
 [    42  90000]
 [    38  59000]
 [    60 108000]
 [    22  63000]
 [    24  32000]
 [    46  59000]
 [    48 134000]
 [    41  72000]
 [    50  44000]
 [    38  71000]
 [    24  23000]
 [    35  61000]
 [    37  80000]
 [    24  27000]
 [    26  84000]
 [    34  25000]
 [    36  54000]
 [    21  68000]
 [    41  71000]
 [    60  42000]
 [    52  90000]
 [    20  23000]
 [    51  23000]
 [    46  79000]
 [    30  49000]]

In [36]:
print(X_test)

[[    36  33000]
 [    39  61000]
 [    36 118000]
 [    39 122000]
 [    26 118000]
 [    38  65000]
 [    20  36000]
 [    49  89000]
 [    31  18000]
 [    48 141000]
 [    34  72000]
 [    39  73000]
 [    35  72000]
 [    48 131000]
 [    53  82000]
 [    56 133000]
 [    60  83000]
 [    27  58000]
 [    28  87000]
 [    60 102000]
 [    40  75000]
 [    50  88000]
 [    44 139000]
 [    47  43000]
 [    45  26000]
 [    26  15000]
 [    58  47000]
 [    49  74000]
 [    53  34000]
 [    52 114000]
 [    39  42000]
 [    19  76000]
 [    18  86000]
 [    57  74000]
 [    27  84000]
 [    30  80000]
 [    22  18000]
 [    32  86000]
 [    50  20000]
 [    19  25000]
 [    47 144000]
 [    58 101000]
 [    34 115000]
 [    23  66000]
 [    56  60000]
 [    31 118000]
 [    48  35000]
 [    47 113000]
 [    39  79000]
 [    52  38000]
 [    24  58000]
 [    37  53000]
 [    42  80000]
 [    46  28000]
 [    42  73000]
 [    37  62000]
 [    60  42000]
 [    36  52000]
 [    58  95000]
 [    43 129000]
 [    27  89000]
 [    23  82000]
 [    38 112000]
 [    35  50000]
 [    36  99000]
 [    37 144000]
 [    26  35000]
 [    42  70000]
 [    43 133000]
 [    38  50000]
 [    46  96000]
 [    35  44000]
 [    38 113000]
 [    39  71000]
 [    26  52000]
 [    54 108000]
 [    33  51000]
 [    26  16000]
 [    30  87000]
 [    35  60000]]

In [38]:
print(y_train)

[0 1 1 0 0 0 1 0 1 0 1 1 1 0 0 1 1 1 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0
 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0
 1 1 0 0 0 1 0 1 1 0 0 0 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1
 0 1 0 0 0 0 1 0 0 1 0 0 1 1 0 1 0 0 0 1 1 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1
 0 1 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1
 0 1 0 1 0 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 1
 0 1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 1 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1
 0 0 1 1 1 0 0 0 1 0 1 1 1 0 0 1 0 0 0 1 0 0 0 1 0 1 0 1 0 1 1 0 0 1 0 0 1
 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0]

In [39]:
print(y_test)

[0 0 1 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 1 0 1 1 0 1 0 1 0 1 0 0 0 0 1 0 0 0
 0 1 0 1 1 0 0 1 1 1 1 0 1 0 0 1 1 1 0 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0
 0 1 0 0 0 0]

# **Feature Scaling**

In [40]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [41]:
print(X_train)

[[-0.80330081 -1.19121795]
 [ 0.75697997 -1.36859801]
 [ 0.85449752  1.43991958]
 [-0.51074816 -1.48685138]
 [-1.48592365  0.37563923]
 [-1.19337101  0.55301929]
 [ 1.04953262 -1.04340124]
 [-0.21819552 -0.30431766]
 [ 0.95201507 -1.33903467]
 [-1.09585346 -1.07296458]
 [-0.51074816  1.97205975]
 [ 2.21974321 -1.0138379 ]
 [ 1.43960282 -1.39816136]
 [ 0.07435713 -0.39300769]
 [-1.19337101  0.64170932]
 [ 2.02470811 -0.89558452]
 [ 1.14705017  0.58258263]
 [-0.02316042  0.2869492 ]
 [-0.21819552  0.25738586]
 [-0.31571307 -0.74776781]
 [-1.68095875 -0.57038775]
 [ 0.85449752  0.58258263]
 [-0.60826571 -1.0138379 ]
 [ 0.95201507 -1.13209127]
 [-0.21819552 -0.54082441]
 [ 0.17187468  0.81908937]
 [-0.41323061  1.32166621]
 [ 1.14705017  0.52345594]
 [ 0.75697997  0.31651254]
 [ 0.65946243 -0.86602118]
 [ 0.36690978 -0.27475432]
 [ 0.46442733 -0.45213438]
 [-0.21819552  0.13913248]
 [ 0.36690978  0.10956914]
 [-0.99833591  0.81908937]
 [-0.70578326  1.41035623]
 [ 0.36690978 -0.48169772]
 [ 0.36690978 -0.48169772]
 [-1.68095875  0.40520257]
 [ 0.85449752 -0.80689449]
 [-0.99833591 -1.10252793]
 [-0.21819552  0.0800058 ]
 [ 1.14705017 -1.19121795]
 [-0.21819552  0.67127266]
 [-0.02316042  0.19825917]
 [-0.51074816  1.43991958]
 [-0.12067797  0.19825917]
 [-1.68095875  0.52345594]
 [ 0.07435713 -0.54082441]
 [ 1.14705017 -0.95471121]
 [ 0.26939223 -0.09737426]
 [-0.02316042  0.25738586]
 [ 2.21974321 -0.65907778]
 [ 1.04953262  2.06074978]
 [ 0.26939223  0.0800058 ]
 [-0.12067797 -0.15650095]
 [-1.09585346  0.37563923]
 [-0.41323061 -1.10252793]
 [ 0.36690978 -0.51126106]
 [ 0.85449752  0.16869583]
 [-1.87599385  0.40520257]
 [-0.02316042 -1.04340124]
 [-0.21819552 -0.45213438]
 [-0.90081836 -0.27475432]
 [-0.02316042  0.0800058 ]
 [-1.87599385 -0.71820447]
 [ 0.07435713 -0.21562763]
 [-0.21819552 -0.09737426]
 [-0.60826571 -0.06781092]
 [ 0.95201507 -1.27990798]
 [ 0.46442733  1.05559612]
 [-1.7784763  -1.45728804]
 [-1.5834412   0.10956914]
 [-0.90081836 -1.07296458]
 [ 1.43960282  2.4155099 ]
 [ 1.53712037  1.05559612]
 [-1.19337101  0.34607588]
 [-1.09585346  0.10956914]
 [-1.09585346 -1.57554141]
 [ 0.26939223  2.17900315]
 [-0.21819552 -0.89558452]
 [ 1.92719056  1.58773629]
 [ 0.36690978  0.55301929]
 [-1.29088856  0.61214597]
 [-0.02316042 -0.48169772]
 [-0.21819552  1.17384949]
 [-0.51074816  0.93734275]
 [-0.21819552  2.32681987]
 [-1.7784763  -1.25034464]
 [ 0.85449752  0.40520257]
 [ 0.95201507  1.08515946]
 [ 0.75697997 -0.68864112]
 [ 0.07435713 -0.51126106]
 [-0.02316042  0.73039934]
 [-0.80330081 -0.74776781]
 [ 0.36690978 -1.13209127]
 [ 0.26939223 -0.24519098]
 [-0.99833591  0.58258263]
 [-0.99833591  0.64170932]
 [ 0.17187468  0.0800058 ]
 [-1.3884061  -1.19121795]
 [ 1.34208527  2.29725653]
 [-1.3884061  -0.15650095]
 [-0.02316042  0.34607588]
 [ 0.26939223 -0.62951444]
 [ 1.04953262 -1.16165461]
 [-0.21819552 -0.27475432]
 [-1.09585346 -1.13209127]
 [ 0.17187468  1.1147228 ]
 [-0.90081836  0.46432926]
 [ 2.12222566  0.22782251]
 [ 0.26939223 -0.33388101]
 [-0.21819552  0.84865272]
 [-1.09585346  0.52345594]
 [ 0.36690978 -0.15650095]
 [-0.80330081 -0.62951444]
 [-1.09585346 -1.51641473]
 [ 2.02470811 -1.33903467]
 [-0.70578326 -0.18606429]
 [-1.19337101 -1.04340124]
 [ 2.12222566 -1.16165461]
 [-0.90081836 -0.92514787]
 [ 0.17187468  0.25738586]
 [ 0.95201507  1.14428615]
 [ 1.43960282  2.06074978]
 [-0.80330081 -0.74776781]
 [-0.99833591  2.03118644]
 [-1.29088856 -0.39300769]
 [ 0.26939223  0.10956914]
 [-1.5834412  -1.54597807]
 [ 1.92719056 -1.25034464]
 [-0.70578326  1.97205975]
 [ 1.04953262  1.49904626]
 [ 0.26939223 -0.33388101]
 [-0.21819552  0.19825917]
 [-0.90081836 -0.71820447]
 [-0.02316042  0.16869583]
 [-0.21819552 -1.2207813 ]
 [-0.02316042  0.31651254]
 [-0.51074816  1.52860961]
 [-0.80330081  0.19825917]
 [-0.70578326 -1.51641473]
 [-1.19337101  0.31651254]
 [ 0.26939223  1.14428615]
 [-1.29088856 -1.45728804]
 [ 0.36690978  0.10956914]
 [ 0.07435713 -0.21562763]
 [-0.12067797  2.23812984]
 [ 0.46442733 -0.1269376 ]
 [ 1.04953262 -1.04340124]
 [ 1.04953262 -1.13209127]
 [-1.3884061  -1.4277247 ]
 [ 1.73215547  1.82424304]
 [-0.80330081  2.35638321]
 [ 0.46442733 -0.09737426]
 [-0.99833591 -0.42257103]
 [-0.02316042 -0.39300769]
 [-1.19337101 -1.36859801]
 [ 2.12222566  2.2085665 ]
 [ 0.46442733 -0.42257103]
 [-0.99833591 -1.51641473]
 [ 0.95201507 -0.57038775]
 [-0.90081836 -0.27475432]
 [-0.41323061  0.02087911]
 [-0.60826571 -0.00868423]
 [-0.21819552 -1.33903467]
 [-0.21819552 -1.36859801]
 [ 1.92719056 -1.04340124]
 [-0.70578326  1.14428615]
 [ 0.85449752 -1.33903467]
 [ 0.36690978 -0.24519098]
 [-0.41323061 -0.80689449]
 [-0.41323061 -0.24519098]
 [ 0.95201507 -0.62951444]
 [-0.90081836 -0.39300769]
 [ 0.75697997 -1.07296458]
 [-0.21819552  0.19825917]
 [ 2.12222566 -0.77733115]
 [ 0.95201507 -0.54082441]
 [ 0.95201507 -0.51126106]
 [-0.21819552  0.31651254]
 [ 0.17187468 -0.77733115]
 [ 0.26939223  0.2869492 ]
 [-1.3884061  -0.59995109]
 [ 0.17187468  0.19825917]
 [-0.21819552 -0.33388101]
 [ 1.73215547 -0.86602118]
 [-0.60826571  0.0800058 ]
 [-0.90081836  1.61729964]
 [ 0.46442733  0.34607588]
 [ 0.26939223 -0.27475432]
 [ 1.04953262  0.16869583]
 [-1.5834412   0.58258263]
 [ 1.53712037  0.10956914]
 [-0.99833591 -0.30431766]
 [-0.21819552 -0.62951444]
 [-0.90081836  0.61214597]
 [-1.09585346  0.34607588]
 [-0.51074816  1.43991958]
 [ 0.46442733  0.19825917]
 [-0.41323061  2.38594656]
 [ 0.36690978  0.34607588]
 [-0.60826571 -0.30431766]
 [ 0.17187468  1.94249641]
 [-0.99833591 -1.4277247 ]
 [-0.80330081  0.43476591]
 [-1.7784763   0.05044245]
 [-1.7784763   0.4938926 ]
 [-0.80330081 -0.21562763]
 [ 0.17187468  1.94249641]
 [-0.60826571  0.22782251]
 [ 0.36690978  0.10956914]
 [-1.09585346  0.34607588]
 [ 0.26939223 -0.21562763]
 [-0.21819552 -1.27990798]
 [ 1.04953262  0.81908937]
 [ 0.46442733  2.38594656]
 [-0.90081836  0.31651254]
 [ 1.34208527  1.94249641]
 [-0.41323061 -1.19121795]
 [ 0.46442733 -0.42257103]
 [ 0.75697997 -1.36859801]
 [-0.02316042 -0.33388101]
 [-0.31571307  1.29210286]
 [-0.21819552 -0.86602118]
 [-1.48592365 -1.2207813 ]
 [-0.21819552  0.10956914]
 [ 0.17187468 -0.27475432]
 [-1.68095875  0.16869583]
 [ 0.85449752 -1.07296458]
 [-1.09585346 -0.74776781]
 [-0.80330081  0.43476591]
 [ 1.73215547  1.67642632]
 [-0.02316042  2.29725653]
 [ 0.75697997  1.85380638]
 [-0.41323061 -0.74776781]
 [ 0.36690978 -0.68864112]
 [ 0.46442733  0.31651254]
 [-0.02316042  2.03118644]
 [-1.29088856  0.46432926]
 [-0.51074816 -1.48685138]
 [ 1.82967301  1.05559612]
 [ 1.14705017 -0.86602118]
 [-0.90081836  0.4938926 ]
 [ 1.53712037  2.2085665 ]
 [-0.70578326  0.61214597]
 [ 1.92719056 -0.24519098]
 [ 0.26939223  0.19825917]
 [ 0.36690978  0.31651254]
 [-1.68095875  0.40520257]
 [-1.48592365 -0.39300769]
 [-0.21819552  0.58258263]
 [ 1.63463792  0.05044245]
 [-0.60826571 -1.57554141]
 [ 1.24456772 -0.95471121]
 [ 0.46442733 -0.09737426]
 [-0.31571307 -0.74776781]
 [ 0.46442733  1.17384949]
 [ 1.63463792 -1.25034464]
 [-1.7784763  -1.39816136]
 [-0.12067797 -0.54082441]
 [-0.02316042  0.05044245]
 [-0.12067797  1.70598967]
 [ 0.95201507 -1.4277247 ]
 [-0.70578326  0.31651254]
 [ 2.12222566  0.43476591]
 [-0.80330081  0.34607588]
 [ 0.56194488  1.29210286]
 [ 0.07435713  0.34607588]
 [ 2.02470811  2.23812984]
 [-0.12067797  1.67642632]
 [ 1.14705017 -1.19121795]
 [-1.87599385 -0.48169772]
 [-0.70578326 -1.57554141]
 [ 2.12222566  0.58258263]
 [-0.99833591 -0.33388101]
 [ 0.07435713  0.0800058 ]
 [-0.60826571  0.61214597]
 [ 0.95201507 -1.0138379 ]
 [-0.60826571  0.16869583]
 [-0.02316042  0.10956914]
 [ 0.26939223 -0.33388101]
 [ 2.12222566  1.82424304]
 [ 1.14705017 -0.09737426]
 [ 1.04953262  0.64170932]
 [ 0.85449752 -1.36859801]
 [ 1.63463792  1.05559612]
 [-0.21819552 -1.4277247 ]
 [ 1.14705017  2.14943981]
 [ 1.04953262 -0.80689449]
 [-0.21819552 -0.39300769]
 [-0.12067797 -0.24519098]
 [-0.51074816  2.4155099 ]
 [-1.87599385 -0.00868423]
 [-1.29088856 -0.39300769]
 [ 0.46442733  0.64170932]
 [ 0.07435713 -0.27475432]
 [ 2.21974321  1.17384949]
 [-1.48592365 -0.15650095]
 [-1.29088856 -1.07296458]
 [ 0.85449752 -0.27475432]
 [ 1.04953262  1.94249641]
 [ 0.36690978  0.10956914]
 [ 1.24456772 -0.71820447]
 [ 0.07435713  0.0800058 ]
 [-1.29088856 -1.33903467]
 [-0.21819552 -0.21562763]
 [-0.02316042  0.34607588]
 [-1.29088856 -1.2207813 ]
 [-1.09585346  0.46432926]
 [-0.31571307 -1.27990798]
 [-0.12067797 -0.42257103]
 [-1.5834412  -0.00868423]
 [ 0.36690978  0.0800058 ]
 [ 2.21974321 -0.77733115]
 [ 1.43960282  0.64170932]
 [-1.68095875 -1.33903467]
 [ 1.34208527 -1.33903467]
 [ 0.85449752  0.31651254]
 [-0.70578326 -0.57038775]]

In [42]:
print(X_test)

[[-0.29863069 -1.23842019]
 [-0.02918947 -0.42323911]
 [-0.29863069  1.23623667]
 [-0.02918947  1.35269111]
 [-1.19676812  1.23623667]
 [-0.11900321 -0.30678467]
 [-1.73565058 -1.15107936]
 [ 0.86894796  0.39194198]
 [-0.74769941 -1.67512435]
 [ 0.77913422  1.90584971]
 [-0.47825818 -0.1029894 ]
 [-0.02918947 -0.07387579]
 [-0.38844444 -0.1029894 ]
 [ 0.77913422  1.61471361]
 [ 1.22820293  0.18814671]
 [ 1.49764416  1.67294083]
 [ 1.85689913  0.21726032]
 [-1.10695438 -0.51057994]
 [-1.01714064  0.33371476]
 [ 1.85689913  0.77041891]
 [ 0.06062428 -0.01564857]
 [ 0.9587617   0.36282837]
 [ 0.41987925  1.84762249]
 [ 0.68932047 -0.94728409]
 [ 0.50969299 -1.44221547]
 [-1.19676812 -1.76246518]
 [ 1.67727164 -0.83082965]
 [ 0.86894796 -0.04476218]
 [ 1.22820293 -1.20930658]
 [ 1.13838919  1.11978223]
 [-0.02918947 -0.9763977 ]
 [-1.82546432  0.01346504]
 [-1.91527806  0.30460115]
 [ 1.5874579  -0.04476218]
 [-1.10695438  0.24637393]
 [-0.83751315  0.12991949]
 [-1.55602309 -1.67512435]
 [-0.65788566  0.30460115]
 [ 0.9587617  -1.61689713]
 [-1.82546432 -1.47132908]
 [ 0.68932047  1.99319054]
 [ 1.67727164  0.7413053 ]
 [-0.47825818  1.14889584]
 [-1.46620935 -0.27767106]
 [ 1.49764416 -0.45235272]
 [-0.74769941  1.23623667]
 [ 0.77913422 -1.18019297]
 [ 0.68932047  1.09066862]
 [-0.02918947  0.10080588]
 [ 1.13838919 -1.09285214]
 [-1.37639561 -0.51057994]
 [-0.20881695 -0.65614799]
 [ 0.24025176  0.12991949]
 [ 0.59950673 -1.38398824]
 [ 0.24025176 -0.07387579]
 [-0.20881695 -0.3941255 ]
 [ 1.85689913 -0.9763977 ]
 [-0.29863069 -0.6852616 ]
 [ 1.67727164  0.56662364]
 [ 0.3300655   1.55648639]
 [-1.10695438  0.39194198]
 [-1.46620935  0.18814671]
 [-0.11900321  1.06155501]
 [-0.38844444 -0.74348882]
 [-0.29863069  0.68307808]
 [-0.20881695  1.99319054]
 [-1.19676812 -1.18019297]
 [ 0.24025176 -0.16121662]
 [ 0.3300655   1.67294083]
 [-0.11900321 -0.74348882]
 [ 0.59950673  0.59573725]
 [-0.38844444 -0.91817048]
 [-0.11900321  1.09066862]
 [-0.02918947 -0.13210301]
 [-1.19676812 -0.6852616 ]
 [ 1.31801667  0.94510057]
 [-0.56807192 -0.71437521]
 [-1.19676812 -1.73335157]
 [-0.83751315  0.33371476]
 [-0.38844444 -0.45235272]]

# **Training Model with Training Set**

In [45]:
from sklearn.linear_model import LogisticRegression
cls = LogisticRegression(random_state=1)
cls.fit(X_train, y_train)

LogisticRegression(random_state=1)

# **Predicting Result**

In [ ]:
y_pred = cls.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

# **Confusion Metrix**

# **Visualize Model Result**